function StimArgs = stimPulse_AO(StimArgs)

Results = AO_StartDigitalStimulation(...
    StimArgs.StimChannel, ...
    0, ... first phase delay [ms]
    StimArgs.FirstPhaseAmpl_mA, ...
    StimArgs.FirstPhaseWidth_ms, ...
    StimArgs.SecondPhaseDelay_ms, ...
    StimArgs.SecondPhaseAmpl_mA, ...
    StimArgs.SecondPhaseWidth_ms, ...
    StimArgs.Freq_hz, ...
    StimArgs.Duration_sec, ...
    StimArgs.ReturnChannel);

if Results
    error(['Failed to stimulate with error code ',num2str(Results)])
end

end