function stimulator = stimSetup_cerestim(UserArgs)
%
% Intended to extract relevant details from GUI v1 and construct cerestim
% stimulator object using defineSTIM4. 
% 

    stimulator = defineSTIM4(...
        UserArgs.channel1, UserArgs.channel2, ...
        UserArgs.amp1, UserArgs.amp2, ...
        UserArgs.width1, UserArgs.width2, ...
        UserArgs.interphase, UserArgs.frequency, UserArgs.pulses);

end